# Generated by Django 2.2.3 on 2019-07-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dessert',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('amount', models.IntegerField(max_length=4)),
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('amount', models.IntegerField(max_length=4)),
                ('kind', models.CharField(choices=[('H', 'HOT'), ('C', 'COLD')], max_length=50)),
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('amount', models.IntegerField(max_length=4)),
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
