# Generated by Django 2.2.3 on 2019-07-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0002_auto_20190726_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dessert',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='drink',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
